### ISSUE TITLE
back, forward button color change

### ISSUE THREAD

**Issue by pavelsust** [vpotvin/CaldroidX#1]
I want to change backword and forward button color change. how I can do this

**Comment by vpotvin** [comment]
I suggest consulting the issues and documentation in the orginal library for guidance on styling: https://github.com/roomorama/Caldroid

I don't have time to dig into this but most aspects of the library are styleable and I believe you can simply replace the arrow drawable if you dig into the source code and add a drawable to your project with the exact same name.
